# Generated by Django 4.2.29 on 2026-03-11 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_order_payment_orderitem_refund_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSearchIndex',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('search_vector', models.TextField()),
                ('name_lower', models.CharField(db_index=True, max_length=255)),
                ('category_lower', models.CharField(db_index=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search_index', to='api.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_indexes', to='api.store')),
            ],
            options={
                'verbose_name': 'Product Search Index',
                'verbose_name_plural': 'Product Search Indexes',
                'db_table': 'product_search_index',
                'indexes': [models.Index(fields=['store', 'name_lower'], name='search_store_name_idx'), models.Index(fields=['store', 'category_lower'], name='search_store_category_idx')],
            },
        ),
    ]
