# Generated by Django 4.2.29 on 2026-03-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_product_search_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_type', models.CharField(choices=[('business', 'Business'), ('customer', 'Customer')], db_index=True, max_length=20)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('success', models.BooleanField(db_index=True, default=False)),
                ('failure_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Authentication Log',
                'verbose_name_plural': 'Authentication Logs',
                'db_table': 'authentication_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_type', 'email', '-created_at'], name='auth_log_user_email_idx'), models.Index(fields=['ip_address', '-created_at'], name='auth_log_ip_idx'), models.Index(fields=['success', '-created_at'], name='auth_log_success_idx')],
            },
        ),
    ]
