# Generated by Django 4.2.29 on 2026-03-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_authenticationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
