import React, { useRef, useEffect } from 'react';
import { YStack } from './primitives';

export interface ChatMessage {
  id: string;
  /** 'user' = human message; 'mira' = AI coach response */
  role: 'user' | 'mira';
  content: string;
  timestamp: string;
}

export interface MiraAlertItem {
  id: string;
  /** Alert category (e.g. 'overspend', 'budget_warning') — used for icon/color selection */
  type: string;
  message: string;
  /** Present when the alert is scoped to a specific FlowSheet period */
  flowSheetId?: string;
  createdAt: string;
}

export interface AICoachPanelProps {
  messages: ChatMessage[];
  /** Proactive alerts generated by Mira (e.g. overspend warnings) */
  alerts: MiraAlertItem[];
  /** True while a query is in-flight to the Mira backend */
  isQuerying: boolean;
  /** True while the initial alerts list is being fetched */
  isLoadingAlerts: boolean;
  /** ID of the alert currently being dismissed — used to show per-card loading state */
  isDismissingId?: string;
  /** True when the Gemini/Mira service is unavailable; disables input and shows a banner */
  unavailable?: boolean;
  onSubmitQuery: (message: string) => void;
  onDismissAlert: (id: string) => void;
}

export function AICoachPanel({
  messages,
  alerts,
  isQuerying,
  isLoadingAlerts,
  isDismissingId,
  unavailable = false,
  onSubmitQuery,
  onDismissAlert,
}: AICoachPanelProps) {
  const [input, setInput] = React.useState('');
  // Ref attached to a sentinel div at the bottom of the message list — used to auto-scroll
  const messagesEndRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    // Scroll to the latest message whenever the messages array changes
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  const handleSubmit = () => {
    const trimmed = input.trim();
    // Guard: don't send empty strings, concurrent requests, or when service is down
    if (!trimmed || isQuerying || unavailable) return;
    onSubmitQuery(trimmed);
    setInput('');
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    // Enter submits; Shift+Enter inserts a newline (standard chat UX)
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSubmit();
    }
  };

  // Disabled when there's nothing to send, a request is pending, or Mira is down
  const sendDisabled = !input.trim() || isQuerying || unavailable;

  return (
    <YStack style={{ display: 'flex', flexDirection: 'column', gap: 0, height: '100%' }}>
      {/* Unavailability banner — task 25.5 */}
      {unavailable && (
        <div
          role="status"
          aria-live="polite"
          style={{
            padding: '10px 16px',
            background: '#FEF3C7',
            borderRadius: 8,
            fontSize: 13,
            color: '#92400E',
            marginBottom: 12,
          }}
        >
          Coach is unavailable right now. Other app features are unaffected.
        </div>
      )}

      {/* Proactive alert cards (task 25.3).
          Section is hidden entirely when empty to avoid an orphaned "Alerts" heading. */}
      {(isLoadingAlerts || alerts.length > 0) && (
        <section aria-label="Mira alerts" style={{ marginBottom: 16 }}>
          <h2
            style={{
              fontSize: 12,
              fontWeight: 600,
              color: '#A8A29E',
              textTransform: 'uppercase',
              letterSpacing: '0.05em',
              margin: '0 0 8px',
            }}
          >
            Alerts
          </h2>
          {isLoadingAlerts ? (
            <div role="status" style={{ fontSize: 13, color: '#A8A29E', padding: '8px 0' }}>
              Loading alerts…
            </div>
          ) : (
            <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
              {alerts.map((alert) => (
                <AlertCard
                  key={alert.id}
                  alert={alert}
                  isDismissing={isDismissingId === alert.id}
                  onDismiss={() => onDismissAlert(alert.id)}
                />
              ))}
            </div>
          )}
        </section>
      )}

      {/* Chat log (task 25.1). role="log" + aria-live="polite" announces new messages
          to screen readers without interrupting ongoing speech. */}
      <div
        role="log"
        aria-label="Mira conversation"
        aria-live="polite"
        style={{
          flex: 1,
          overflowY: 'auto',
          display: 'flex',
          flexDirection: 'column',
          gap: 12,
          paddingBottom: 8,
          minHeight: 200,
          maxHeight: 420,
        }}
      >
        {messages.length === 0 && !unavailable && (
          <div style={{ padding: '24px 0', textAlign: 'center' }}>
            <p style={{ fontSize: 14, color: '#A8A29E', margin: '0 0 4px' }}>
              Hi, I'm Mira — your budgeting coach.
            </p>
            <p style={{ fontSize: 13, color: '#D6D3D1', margin: 0 }}>
              Ask me anything about your budget.
            </p>
          </div>
        )}

        {messages.map((msg) => (
          <MessageBubble key={msg.id} message={msg} />
        ))}

        {/* Loading indicator during query — task 25.2 */}
        {isQuerying && <TypingIndicator />}

        <div ref={messagesEndRef} aria-hidden="true" />
      </div>

      {/* Input area */}
      <div
        style={{
          borderTop: '1px solid #E7E5E4',
          paddingTop: 12,
          display: 'flex',
          gap: 8,
          alignItems: 'flex-end',
        }}
      >
        <textarea
          value={input}
          onChange={(e) => setInput(e.target.value)}
          onKeyDown={handleKeyDown}
          placeholder={unavailable ? 'Mira is unavailable right now' : 'Ask Mira something…'}
          disabled={isQuerying || unavailable}
          rows={1}
          aria-label="Message to Mira"
          aria-disabled={isQuerying || unavailable}
          style={{
            flex: 1,
            resize: 'none',
            padding: '9px 12px',
            borderRadius: 8,
            border: '1.5px solid #E7E5E4',
            fontSize: 14,
            color: '#1C1917',
            backgroundColor: unavailable ? '#F5F5F4' : '#FFFFFF',
            outline: 'none',
            fontFamily: 'inherit',
            lineHeight: 1.5,
            maxHeight: 120,
            overflowY: 'auto',
          }}
        />
        <button
          type="button"
          onClick={handleSubmit}
          disabled={sendDisabled}
          aria-label="Send message to Mira"
          style={{
            padding: '9px 16px',
            borderRadius: 8,
            border: 'none',
            background: sendDisabled ? '#E7E5E4' : '#44403C',
            color: sendDisabled ? '#A8A29E' : '#FAFAF9',
            fontSize: 14,
            fontWeight: 500,
            cursor: sendDisabled ? 'not-allowed' : 'pointer',
            transition: 'background 0.15s, color 0.15s',
            flexShrink: 0,
            height: 40,
          }}
        >
          {isQuerying ? '…' : 'Send'}
        </button>
      </div>
    </YStack>
  );
}

// ── Sub-components ──────────────────────────────────────────────────────────

/**
 * Single chat bubble. User messages are right-aligned (dark bg); Mira messages
 * are left-aligned (light bg). The bottom corner on the "tail" side is flattened
 * to create a speech-bubble effect.
 */
function MessageBubble({ message }: { message: ChatMessage }) {
  const isUser = message.role === 'user';
  return (
    <div
      style={{ display: 'flex', justifyContent: isUser ? 'flex-end' : 'flex-start' }}
      aria-label={`${isUser ? 'You' : 'Mira'}: ${message.content}`}
    >
      <div
        style={{
          maxWidth: '80%',
          padding: '10px 14px',
          // User: flat bottom-right; Mira: flat bottom-left — standard chat bubble shape
          borderRadius: isUser ? '12px 12px 4px 12px' : '12px 12px 12px 4px',
          background: isUser ? '#44403C' : '#F5F5F4',
          color: isUser ? '#FAFAF9' : '#1C1917',
          fontSize: 14,
          lineHeight: 1.55,
          whiteSpace: 'pre-wrap', // preserves newlines in Mira's formatted responses
          wordBreak: 'break-word',
        }}
      >
        {message.content}
      </div>
    </div>
  );
}

/**
 * Three-dot wave animation shown while Mira is processing a query (task 25.2).
 * Each dot staggers by 200ms to create a wave effect. The keyframe is inlined
 * to avoid a global stylesheet dependency in the shared UI package.
 */
function TypingIndicator() {
  return (
    <div
      role="status"
      aria-label="Mira is thinking"
      style={{ display: 'flex', justifyContent: 'flex-start' }}
    >
      <div
        style={{
          padding: '10px 14px',
          borderRadius: '12px 12px 12px 4px',
          background: '#F5F5F4',
          display: 'flex',
          gap: 4,
          alignItems: 'center',
        }}
      >
        {[0, 1, 2].map((i) => (
          <span
            key={i}
            aria-hidden="true"
            style={{
              width: 6,
              height: 6,
              borderRadius: '50%',
              background: '#A8A29E',
              animation: `mira-dot 1.2s ease-in-out ${i * 0.2}s infinite`,
            }}
          />
        ))}
        <style>{`
          @keyframes mira-dot {
            0%, 80%, 100% { transform: scale(0.8); opacity: 0.5; }
            40% { transform: scale(1); opacity: 1; }
          }
        `}</style>
      </div>
    </div>
  );
}

/**
 * Proactive alert card with a dismiss button.
 * While dismissal is in-flight, the card fades to 50% opacity and the button
 * is disabled to prevent duplicate dismiss requests.
 */
function AlertCard({
  alert,
  isDismissing,
  onDismiss,
}: {
  alert: MiraAlertItem;
  isDismissing: boolean;
  onDismiss: () => void;
}) {
  return (
    <div
      role="alert"
      aria-label={`Mira alert: ${alert.message}`}
      style={{
        display: 'flex',
        alignItems: 'flex-start',
        gap: 10,
        padding: '10px 14px',
        background: '#FEF9F0',
        border: '1px solid #F5E6C8',
        borderRadius: 8,
        opacity: isDismissing ? 0.5 : 1,
        transition: 'opacity 0.2s',
      }}
    >
      <span aria-hidden="true" style={{ fontSize: 16, flexShrink: 0, marginTop: 1 }}>
        ⚠️
      </span>
      <p style={{ flex: 1, fontSize: 13, color: '#44403C', margin: 0, lineHeight: 1.5 }}>
        {alert.message}
      </p>
      <button
        type="button"
        onClick={onDismiss}
        disabled={isDismissing}
        aria-label="Dismiss alert"
        style={{
          background: 'none',
          border: 'none',
          color: '#A8A29E',
          fontSize: 14,
          cursor: isDismissing ? 'not-allowed' : 'pointer',
          padding: '0 2px',
          flexShrink: 0,
          lineHeight: 1,
        }}
      >
        ✕
      </button>
    </div>
  );
}
